/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'dark-bg': '#0a0a0f',
        'dark-panel': '#111118',
        'light-bg': '#f8f8fa',
        'white': '#ffffff',
        'primary': '#00ff88',
        'primary-dark': '#00cc6a',
        'secondary': '#3b82f6',
        'accent': '#ff6b35',
        'warning': '#f59e0b',
        'danger': '#ef4444',
        'text-muted': '#6b7280',
        'text-light': '#9ca3af',
        'border-dark': 'rgba(255, 255, 255, 0.08)',
        'border-light': '#e5e7eb',
      },
      fontFamily: {
        'inter': ['Inter', 'system-ui', 'sans-serif'],
      },
      backgroundImage: {
        'gradient-green-blue': 'linear-gradient(to right, #00ff88, #3b82f6)',
        'gradient-dark': 'linear-gradient(to bottom, #0a0a0f, #111118)',
        'gradient-hero': 'linear-gradient(135deg, #0a0a0f 0%, #111118 50%, rgba(0, 255, 136, 0.05) 100%)',
      },
      boxShadow: {
        'glow-green': '0 0 20px rgba(0, 255, 136, 0.3), 0 0 40px rgba(0, 255, 136, 0.1)',
        'glow-green-sm': '0 0 10px rgba(0, 255, 136, 0.2)',
        'glow-blue': '0 0 20px rgba(59, 130, 246, 0.3), 0 0 40px rgba(59, 130, 246, 0.1)',
        'card-hover': '0 20px 40px rgba(0, 0, 0, 0.08), 0 0 20px rgba(0, 255, 136, 0.15)',
        'card-dark': '0 8px 24px rgba(0, 0, 0, 0.4)',
        'btn-primary': '0 4px 16px rgba(0, 255, 136, 0.4)',
        'btn-secondary': '0 4px 16px rgba(59, 130, 246, 0.4)',
      },
      borderRadius: {
        'xl': '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'float': 'float 3s ease-in-out infinite',
      },
      keyframes: {
        'fadeIn': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slideUp': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slideDown': {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'pulseGlow': {
          '0%, 100%': { boxShadow: '0 0 5px rgba(0, 255, 136, 0.4)' },
          '50%': { boxShadow: '0 0 20px rgba(0, 255, 136, 0.8)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
      screens: {
        'xs': '475px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
      letterSpacing: {
        'btn': '0.1em',
        'heading': '0.05em',
        'uppercase': '0.08em',
      },
      lineClamp: {
        '2': '2',
        '3': '3',
      },
    },
  },
  plugins: [
    function({ addUtilities }) {
      const newUtilities = {
        '.text-gradient': {
          backgroundImage: 'linear-gradient(to right, #00ff88, #3b82f6)',
          WebkitBackgroundClip: 'text',
          WebkitTextFillColor: 'transparent',
          backgroundClip: 'text',
        },
        '.glow-green': {
          boxShadow: '0 0 20px rgba(0, 255, 136, 0.3), 0 0 40px rgba(0, 255, 136, 0.1)',
        },
        '.glow-blue': {
          boxShadow: '0 0 20px rgba(59, 130, 246, 0.3), 0 0 40px rgba(59, 130, 246, 0.1)',
        },
        '.card-hover': {
          transition: 'all 0.3s ease',
          '&:hover': {
            transform: 'translateY(-4px)',
            boxShadow: '0 20px 40px rgba(0, 0, 0, 0.08), 0 0 20px rgba(0, 255, 136, 0.15)',
          },
        },
        '.sticky-bottom': {
          position: 'sticky',
          bottom: '0',
          zIndex: '50',
        },
        '.scrollbar-hide': {
          scrollbarWidth: 'none',
          msOverflowStyle: 'none',
          '&::-webkit-scrollbar': {
            display: 'none',
          },
        },
        '.line-clamp-2': {
          display: '-webkit-box',
          WebkitLineClamp: '2',
          WebkitBoxOrient: 'vertical',
          overflow: 'hidden',
        },
        '.line-clamp-3': {
          display: '-webkit-box',
          WebkitLineClamp: '3',
          WebkitBoxOrient: 'vertical',
          overflow: 'hidden',
        },
        '.btn-filled': {
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '0.75rem 1.5rem',
          borderRadius: '9999px',
          fontWeight: '700',
          fontSize: '0.875rem',
          letterSpacing: '0.1em',
          textTransform: 'uppercase',
          backgroundColor: '#00ff88',
          color: '#0a0a0f',
          transition: 'all 0.2s ease',
          boxShadow: '0 4px 16px rgba(0, 255, 136, 0.4)',
          '&:hover': {
            backgroundColor: '#00cc6a',
            transform: 'translateY(-1px)',
            boxShadow: '0 6px 20px rgba(0, 255, 136, 0.5)',
          },
        },
        '.btn-outlined': {
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '0.75rem 1.5rem',
          borderRadius: '9999px',
          fontWeight: '700',
          fontSize: '0.875rem',
          letterSpacing: '0.1em',
          textTransform: 'uppercase',
          backgroundColor: 'transparent',
          color: '#00ff88',
          border: '2px solid #00ff88',
          transition: 'all 0.2s ease',
          '&:hover': {
            backgroundColor: 'rgba(0, 255, 136, 0.1)',
            transform: 'translateY(-1px)',
          },
        },
        '.btn-ghost': {
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '0.75rem 1.5rem',
          borderRadius: '9999px',
          fontWeight: '700',
          fontSize: '0.875rem',
          letterSpacing: '0.1em',
          textTransform: 'uppercase',
          backgroundColor: 'transparent',
          color: '#00ff88',
          transition: 'all 0.2s ease',
          '&:hover': {
            backgroundColor: 'rgba(0, 255, 136, 0.08)',
          },
        },
        '.badge-sale': {
          padding: '0.25rem 0.75rem',
          borderRadius: '9999px',
          backgroundColor: '#ef4444',
          color: '#ffffff',
          fontSize: '0.75rem',
          fontWeight: '800',
          letterSpacing: '0.05em',
          textTransform: 'uppercase',
        },
        '.badge-new': {
          padding: '0.25rem 0.75rem',
          borderRadius: '9999px',
          backgroundColor: '#00ff88',
          color: '#0a0a0f',
          fontSize: '0.75rem',
          fontWeight: '800',
          letterSpacing: '0.05em',
          textTransform: 'uppercase',
        },
        '.badge-best-seller': {
          padding: '0.25rem 0.75rem',
          borderRadius: '9999px',
          backgroundColor: '#f59e0b',
          color: '#ffffff',
          fontSize: '0.75rem',
          fontWeight: '800',
          letterSpacing: '0.05em',
          textTransform: 'uppercase',
        },
        '.badge-authentic': {
          padding: '0.25rem 0.75rem',
          borderRadius: '9999px',
          backgroundColor: '#3b82f6',
          color: '#ffffff',
          fontSize: '0.75rem',
          fontWeight: '800',
          letterSpacing: '0.05em',
          textTransform: 'uppercase',
        },
        '.trust-badge': {
          display: 'inline-flex',
          alignItems: 'center',
          gap: '0.5rem',
          padding: '0.5rem 1rem',
          borderRadius: '0.75rem',
          backgroundColor: 'rgba(0, 255, 136, 0.08)',
          border: '1px solid rgba(0, 255, 136, 0.2)',
          color: '#00ff88',
          fontSize: '0.875rem',
          fontWeight: '600',
        },
        '.mega-menu-panel': {
          position: 'absolute',
          left: '50%',
          transform: 'translateX(-50%)',
          width: 'min(1200px, calc(100vw - 4rem))',
          backgroundColor: '#ffffff',
          borderRadius: '1.5rem',
          boxShadow: '0 25px 50px rgba(0, 0, 0, 0.15)',
          overflow: 'hidden',
          zIndex: '60',
        },
      };
      addUtilities(newUtilities);
    },
  ],
}
